### ISSUE TITLE
Halo 2 For Windows Vista crashes with D3d9Wrapper

### ISSUE THREAD

**Issue by MrEWhite** [elishacloud/dxwrapper#291]
Attempting to play Halo 2 for Windows Vista with dxwrapper and EnableD3d9Wrapper set to 1 crashes the game past the initial "Halo 2" logo that shows upon booting the game. Attached is my dxwrapper log.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16716614/dxwrapper-halo2.log)

**Comment by elishacloud** [comment]
Can you try with the latest build.  Just replace the dxwrapper.dll file with the one in this package:  [dxwrapper.zip](https://github.com/user-attachments/files/16716977/dxwrapper.zip)

**Comment by MrEWhite** [comment]
> Can you try with the latest build. Just replace the dxwrapper.dll file with the one in this package: [dxwrapper.zip](https://github.com/user-attachments/files/16716977/dxwrapper.zip)

Same crash as far as I can tell. Attached is the log generated from that build.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16717064/dxwrapper-halo2.log)

**Comment by elishacloud** [comment]
Just from the logs it looks like the game is creating a second device before releasing the first.  Can you try with the debug log and send the full log back?

Here is the debug log.  Just pull the dxwrapper.dll file from this:  [dxwrapper.zip](https://github.com/user-attachments/files/16717253/dxwrapper.zip)

**Comment by MrEWhite** [comment]
> Just from the logs it looks like the game is creating a second device before releasing the first. Can you try with the debug log and send the full log back?
> 
> Here is the debug log. Just pull the dxwrapper.dll file from this: [dxwrapper.zip](https://github.com/user-attachments/files/16717253/dxwrapper.zip)

Sure, here ya go.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16717304/dxwrapper-halo2.log)

**Comment by MrEWhite** [comment]
Just saw the commit, tried it and it still crashed. Here's the debug log.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16720892/dxwrapper-halo2.log)

**Comment by elishacloud** [comment]
Thanks!  I fixed an issue that I found from your logs.  I see what is happening now.  The game creates a `IID_IDirect3DDevice9Ex` interface and then queries for `IID_IDirect3DDevice9`.  I wrote my wrapper never expecting that to happen.  Let me see if there is a good way to fix that.

**Comment by elishacloud** [comment]
I don't really have a good way to test this use case but I put a fix (just a hack for now) in for it.  Let me know if you still have issues with the latest build.

**Comment by MrEWhite** [comment]
That did fix it! The game does start now.

**Comment by elishacloud** [comment]
Ok, great.  Thanks for the confirmation.

**Comment by elishacloud** [comment]
I put a proper fix in for this.  If you have a chance I would appreciate it if you can test with the latest build to make sure it still works.  Thanks!

**Comment by MrEWhite** [comment]
> I put a proper fix in for this. If you have a chance I would appreciate it if you can test with the latest build to make sure it still works. Thanks!
The new build freezes and needs to be closed via task manager. Attached is the debug log.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16733099/dxwrapper-halo2.log)

**Comment by MrEWhite** [comment]
> I put a proper fix in for this. If you have a chance I would appreciate it if you can test with the latest build to make sure it still works. Thanks!
That seems to crash on my end.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16733163/dxwrapper-halo2.log)

**Comment by elishacloud** [comment]
That is the same place it crashed before.  Let me see what I did wrong here.

**Comment by MrEWhite** [comment]
Using the build that was working with the D3d9Wrapper before, I went ahead and tested a few things, and it looks like the game still has the same few issues as I was having natively. On modern Nvidia cards (seemingly a driver related thing), there are two issues with the game visually. First is that anti-aliasing causes seams throughout the map, and secondly, on the singleplayer campaign level Delta Halo, leaves on a few trees near the start of the level don't render at all. Both of these issues seem to be fixed with dgVoodoo2, but that has a fair share of it's own issues with the game. Here are some screenshots showing the issues:

dgVoodoo2:
![Halo 2 8_23_2024 6_28_17 PM](https://github.com/user-attachments/assets/7231e213-4d18-4462-9075-f2d09bbe05e1)
![Halo 2 8_23_2024 6_27_36 PM](https://github.com/user-attachments/assets/c519f465-15e3-4d9d-b2f9-314dbc817185)

dxwrapper w/ D3d9Wrapper on:
![Screenshot 8_23_2024 6_34_05 PM](https://github.com/user-attachments/assets/a4003d1e-4de6-4452-848c-12d8ff8199da)
![Halo 2 8_23_2024 6_35_40 PM](https://github.com/user-attachments/assets/b59074cb-e8af-4203-b880-3aa3994c9bdf)

**Comment by elishacloud** [comment]
> First is that anti-aliasing enabled through the game's settings causes seams throughout the map

Yeah.  This is an issue with vertices that the game uses.  I have been meaning to put a fix in for this but it is lower on my priority.  See [this thread](https://github.com/narzoul/DDrawCompat/issues/344#issuecomment-2298655953) for a better explanation.

I see this with a number of games, including Knight Rider 2 and Star Trek: Armada 1.  Older games, but the same issue.  Keep in mind that the MSAA uses edge aliasing which can make the edges semi or full transparent, thus showing this issue.  A better solution is to use SSAA, but I have not built an engine for that here.  I did build one for [Silent Hill 2 Enhanced Edition](https://github.com/elishacloud/Silent-Hill-2-Enhancements).

> secondly, on the singleplayer campaign level Delta Halo, leaves on a few trees near the start of the level don't render at all.

My D3d9Wrapper does not have too many fixes in it for Direct3D9.  Most of the fixes I have are for older games Direct3D8 and older.  I would need to figure out what is causing this and then put a fix in.  I am just wrapping the dll and then calling the native APIs with not many changes.

dgVoodoo2 is actually converting all the functions to Direct3D11/12.  It is closed source so I cannot really see what is happening and I am not good at debugging compiled code to check it out.  However, this is not really needed as there is a way to cover them all to Direct3D12, built into Windows.  See [here](https://github.com/microsoft/D3D9On12).  I added support for this in dxwrapper already.

However, I do want to fix the crash in my wrapper.  Can you try with this debug version.  I added extra logging to try and see what is going on:  [dxwrapper.zip](https://github.com/user-attachments/files/16734284/dxwrapper.zip)

**Comment by MrEWhite** [comment]
> > First is that anti-aliasing enabled through the game's settings causes seams throughout the map
> 
> Yeah. This is an issue with vertices that the game uses. I have been meaning to put a fix in for this but it is lower on my priority. See [this thread](https://github.com/narzoul/DDrawCompat/issues/344#issuecomment-2298655953) for a better explanation.
> 
> I see this with a number of games, including Knight Rider 2 and Star Trek: Armada 1. Older games, but the same issue. Keep in mind that the MSAA uses edge aliasing which can make the edges semi or full transparent, thus showing this issue. A better solution is to use SSAA, but I have not built an engine for that here. I did build one for [Silent Hill 2 Enhanced Edition](https://github.com/elishacloud/Silent-Hill-2-Enhancements).
> 
> > secondly, on the singleplayer campaign level Delta Halo, leaves on a few trees near the start of the level don't render at all.
> 
> My D3d9Wrapper does not have too many fixes in it for Direct3D9. Most of the fixes I have are for older games Direct3D8 and older. I would need to figure out what is causing this and then put a fix in. I am just wrapping the dll and then calling the native APIs with not many changes.
> 
> dgVoodoo2 is actually converting all the functions to Direct3D11/12. It is closed source so I cannot really see what is happening and I am not good at debugging compiled code to check it out. However, this is not really needed as there is a way to cover them all to Direct3D12, built into Windows. See [here](https://github.com/microsoft/D3D9On12). I added support for this in dxwrapper already.
> 
> However, I do want to fix the crash in my wrapper. Can you try with this debug version. I added extra logging to try and see what is going on: [dxwrapper.zip](https://github.com/user-attachments/files/16734284/dxwrapper.zip)

Here's the crash log you requested.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16734369/dxwrapper-halo2.log)

I understand you on the other two bits, but quick note on those two issues if it changes anything, I'm pretty sure they both only happen on Nvidia, and work fine on AMD, can't test that myself with an Nvidia card though.

**Comment by MrEWhite** [comment]
Tried the latest commit, still crashes.
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16734526/dxwrapper-halo2.log)

**Comment by elishacloud** [comment]
Can you send me a debug log from one that does not crash?

**Comment by MrEWhite** [comment]
> Can you send me a debug log from one that does not crash?

For some reason, with the debug build, I can't get in game, but with the release one, I can. I'll attach both logs to see if that'll help.
[dxwrapper-halo2-debug.log](https://github.com/user-attachments/files/16734555/dxwrapper-halo2-debug.log)
[dxwrapper-halo2.log](https://github.com/user-attachments/files/16734558/dxwrapper-halo2.log)

**Comment by elishacloud** [comment]
I am not sure I understand what the game is trying to do here.  It is switching between the IDirect3DDevice9 and the IDirect3DDevice9Ex interfaces.  Anyways, I reverted most of the recent changes to try and put it back to the working condition and added the code to that.  My other ways of trying to fix this did not work.

> For some reason, with the debug build, I can't get in game

Yeah, I had a bug in the debug build then.  It has been fixed.

> I'm pretty sure they both only happen on Nvidia, and work fine on AMD, can't test that myself with an Nvidia card though.

Yes, I have seen a number of these.  In the Silent Hill 2 Enhanced Edition project we put a number of fixes in specific to Nvidia.  Maybe Nvidia is more struct with the interpretation of how things should work, whereas some of these older games are more loose about it.

I will look into these other issues at some point, but I cannot promise when.  I am currently really focused on the `dd7to9` feature.  I am actually trying to clean up some code and get ready for another release.

**Comment by elishacloud** [comment]
BTW: if you get a chance please test the latest build to make sure that works.  I just want to make sure I fully fix this.

**Comment by MrEWhite** [comment]
> BTW: if you get a chance please test the latest build to make sure that works. I just want to make sure I fully fix this.

Debug build still crashes, but release works. I'll still include both logs though. Issue with release that I noticed though is that I need to start up my desktop with the resolution set higher than 1080p, the limit for the game, or else the game will crash, even with release. The game auto switches to 1080p and if it crashes, the desktop resolution will stick at 1080p. Including a 1080p release log (crashes) and one with my desktop set to 4k (works), as well as a debug build log (crashes no matter what).

[dxwrapper-halo2-1080p.log](https://github.com/user-attachments/files/16734804/dxwrapper-halo2-1080p.log)
[dxwrapper-halo2-debug.log](https://github.com/user-attachments/files/16734805/dxwrapper-halo2-debug.log)
[dxwrapper-halo2-4k.log](https://github.com/user-attachments/files/16734806/dxwrapper-halo2-4k.log)

**Comment by elishacloud** [comment]
Thanks for all your testing.  This is kind of frustrating because I don't quite understand how Direct3D9 works when a game switches between the two interfaces like this game does.  And Microsoft does not have good documentation on this.  Anyways, I appreciate all your testing.  I will review this and see if I can figure out what is happening.

> Issue with release that I noticed though is that I need to start up my desktop with the resolution set higher than 1080p

Does this happen even with the very first build that worked?

**Comment by MrEWhite** [comment]
> Does this happen even with the very first build that worked?

Yes.

**Comment by elishacloud** [comment]
I think maybe the crash in the debug build is happening because of imgui.  I disabled that in the latest build.  Hopefully this will work in the debug build.

> The game auto switches to 1080p and if it crashes, the desktop resolution will stick at 1080p.

This happens because either the game or Windows does not reset the screen after the game crashes because the code is bypassed from the crash.  I added a feature to solve this issue.  If you add the below line to the ini file it should fix this issue.

```ini
ResetScreenRes             = 1
```

**Comment by MrEWhite** [comment]
So, the new build works fine as far as I can tell! But two things I noticed. One is that if I set  ResetScreenRes  = 1, the game will go to the desktop during the intro, and I have to tab back into it, doesn't happen with that disabled though. Another issue with the intro is that it doesn't play the intro video correctly, still just showing the Halo 2 boot logo while the Bungie logo audio plays in the background, and it'll also just skip to the menu part way through said intro.

Was going to upload the log here for this issue, but it actually made a 135 MB log! Here's that uploaded to Mega.
https://mega.nz/file/EW9USLCQ#VjZpEPycBEamwqqIplnbcYQ_Q9yWkuuvixEQ0NRhKfc

**Comment by elishacloud** [comment]
I found a copy of Halo 2 and installed it.  There appears to be three issues with this game.  I am working on a fix.

1. The game did switching between the IDirect3DDevice9 and the IDirect3DDevice9Ex interfaces, which I never implemented and had no way of testing before.
2. The game queries for some device class I have never seen and seems to cause an issue.
3. The Microsoft documentation on CreateAdditionalSwapChain() is wrong.

Issue 1 caused the first crash, which I fixed several times in different ways.
Issue 2 caused the the other crashes that I thought was caused by issue 1.
Issue 3 caused the intro video to disappear.

**Comment by elishacloud** [comment]
I just checked in the fixes for the wrapper for this game.  Note: there is no need to use the `ResetScreenRes` option.  It does not work with this game anyways.

**Comment by MrEWhite** [comment]
New fixes seem to work good! One thing I noticed is that the intro is pretty pixelated compared to native
Native:
![Screenshot 8_24_2024 8_03_03 PM](https://github.com/user-attachments/assets/24917d45-66e7-452e-8397-532a91cc76e1)

dxwrapper:
![Screenshot 2024-08-24 200229](https://github.com/user-attachments/assets/b0c044da-7975-4387-a921-f72dbff892d1)

**Comment by elishacloud** [comment]
From looking at the picture it appears that what is happening is that the video was record at a lower resolution and then stretched to fit a larger window size.  In the native case it uses linear scaling.  In the dxwrapper case it uses point (or nearest neighbor) scaling.  Frankly, from the pictures in GitHub the native one looks more bleary to me.  I am not sire what could cause this.  Let me look into it.

**Comment by Squall-Leonhart** [comment]
> Thanks! I fixed an issue that I found from your logs.
> 
> I see what is happening now. The game creates a `IID_IDirect3DDevice9Ex` interface and then queries for `IID_IDirect3DDevice9`. I wrote my wrapper never expecting that to happen. Let me see if there is a good way to fix that.

They actually did this as an XP blocker, to sell the whole "for Vista", nonsense, the game was made to work on XP within days of launch because it was a simple matter of stubbing the interface out :D

**Comment by elishacloud** [comment]
> New fixes seem to work good! One thing I noticed is that the intro is pretty pixelated compared to native Native:
> 
> dxwrapper: 

This screen is not handled by Direct3D but rather by GDI.  It could be something that dxwrapper calls or hooks that causes this.

You could try adding this line to the ini file, making sure it is disabled:

```ini
DisableHighDPIScaling      = 0
```

**Comment by elishacloud** [comment]
> New fixes seem to work good! One thing I noticed is that the intro is pretty pixelated compared to native

This issue is happening because of the code [here](https://github.com/elishacloud/dxwrapper/blob/409bf81f9fbd1603a476266f002013d54dac5978/d3d9/IDirect3DDevice9Ex.cpp#L70-L79).

**Comment by elishacloud** [comment]
> New fixes seem to work good! One thing I noticed is that the intro is pretty pixelated compared to native

The pixelation comes because I block [certain interfaces](https://github.com/elishacloud/dxwrapper/blob/409bf81f9fbd1603a476266f002013d54dac5978/d3d9/IDirect3DDevice9Ex.cpp#L70-L79).  These are undocumented interfaces that seem to some how change how d3d9 works.  If I allow them then the game crashes in my wrapper when I attempt to call d3d9 functions.  It seems like Microsoft wrote this game and used some undocumented interfaces to make the game work better.

I don't have the time or the skill to reverse engineer what is happening with those interfaces.  If someone else has any idea what those interfaces are doing please let me know.  Otherwise, I probably won't be able to fix this issue.

_Note: I suspect this is the only game with this issue._

**Comment by Squall-Leonhart** [comment]
These are not undocumented, you're looking in the wrong place for them :p

They are UID's for Direct3D9 Video (DXVA2)

**Comment by elishacloud** [comment]
> They are UID's for Direct3D9 Video (DXVA2)

Can you send me a link where these are documented?  I could not find it from a simple Google search.

I was able to find this:  https://learn.microsoft.com/en-us/windows/win32/medfound/direct3d-video-interfaces

**Comment by Squall-Leonhart** [comment]
Sorry, i was actually mislead, and meant to come back and correct myself, had some family loss tonight so been a bit distracted till this moment looking at emails.

 in my digging i found that DXVK also treats these as undocumented and returns no interface, but dxvk doesn't have the pixellation so it may not be connected after all

**Comment by elishacloud** [comment]
It's weird because as far as I can tell that video isn't done using Direct3D9 (maybe it's GDI).  However, it only happens when my wrapper is enabled and my wrapper is a direct pass-through.  Maybe it has to do with my WndProc hook?

I'll need to look into this more.

**Comment by Squall-Leonhart** [comment]
Original is 1920x1080, dxwrapper is 1919x1079, the pixelation is because the scale is odd and no linear scaling is used.

**Comment by Squall-Leonhart** [comment]
The logic inside the if (!DeviceDetails.BufferWidth || !DeviceDetails.BufferHeight) block needs to be updated to check if the window is currently in a full-screen state (borderless windowed).

using GetWindowRect instead of GetClientRect might be an idea too.

**Comment by elishacloud** [comment]
> Original is 1920x1080, dxwrapper is 1919x1079, the pixelation is because the scale is odd and no linear scaling is used.

I am not seeing this on my computer.  It shows the window as 1920x1080 and I can still see the pixelated video.  So I don't think this is the issue.

> using GetWindowRect instead of GetClientRect might be an idea too.

That code isn't the issue.  I tried disabling the code all together and it still has the pixelation issue.

This is a weird issue because I tried disabling pretty much everything I could to make the dxwrapper just a straight through wrapper with no functionality, and the issue remains.

**Comment by Squall-Leonhart** [comment]
~~Are you  handling the alpha plane correctly?~~

~~This intro is 2 bink videos layered over each other~~

the 9ex version has significantly more banding

**Comment by elishacloud** [comment]
> The pixelation comes because I block [certain interfaces](https://github.com/elishacloud/dxwrapper/blob/409bf81f9fbd1603a476266f002013d54dac5978/d3d9/IDirect3DDevice9Ex.cpp#L70-L79).

I just confirmed that these two interfaces are: IID_IDirect3DDxva2Container9 and IID_IDirect3DVideoDevice9.  Enabling either of these interfaces would fix the pixelation issue.  It seems that Halo 2 uses these interfaces for better video quality.  I can make a wrapper to support IID_IDirect3DVideoDevice9 pretty easy, I think.

**Comment by elishacloud** [comment]
I put a fix in for this issue by adding support for IDirect3DVideoDevice9, which is what Halo 2 uses for video playback.

Here is the fixed build:  [dxwrapper.zip](https://github.com/user-attachments/files/23044971/dxwrapper.zip)

**Comment by Squall-Leonhart** [comment]
Bah, i shouldn't have second guessed it when i said they were d3d9 video, i found a brief result on a Chinese forum and couldn't find seconding evidence, but now i see them both used in chromium changesets.

I'm now curious if dxvka is affected, but just has't been reported - it does suffer from desync which might be connected to not implementing them.


I dug up the Change notes for the version of Bink video that was in use around this period of time, and sure enough 1.8b and 1.8j respectively  introduce pixel shaders into the Bink hardware decoder, which requires using the IDirect3DVideoDevice9 interface (for the PC specific set)

1.8a - 1.8b
> Added new Bink for Xbox support code that allows the use of hardware pixel shaders for the YcRcB color conversion. This doubles the playback speed on an Xbox and uses 900 KB less memory and is much higher quality! Using this feature, you can now play 1280x720 HDTV movies on the Xbox!! This is such the right thing to do on an Xbox that it is now the default playback method - if you have old Bink for Xbox code, you should definitely update it.


1.8i - 1.8j
> Added new DirectX 9 pixel shader example code for Win32 and Win64. Pixel shaders are the fastest and highest quality method to display Bink videos. If you are using Bink in a 3D game on Windows, you should definitely update and use the new pixel shader example code.

(No longer Assuming) Bink videos are encoded to YcRcB/YUV420, so the software decoding probably trashed the image quality during RGB conversion, and the software scaled blitting is definitely inferior to the PS 2.0 implementation

**Comment by elishacloud** [comment]
> I'm now curious if dxvka is affected, but just has't been reported - it does suffer from desync which might be connected to not implementing them.

It's not as easy for dxvk to add support for it.  I just had to create a wrapper.  dxvk will have to do the full implementation.

**Comment by elishacloud** [comment]
Closing issue.  Issue is fixed in the latest build of dxwrapper.
